/* BK_T_RequestDao_RequestData.sql */
select
R.REQUEST_ID,
R.TITLE,
R.TITLE_KANA,
R.AUTHOR,
R.AUTHOR_KANA,
R.BOOK_IMG,
R.MEM_ID,
R.COMMENT,
R.REQUEST_STATUS,
RC.REQ_COUNT
from
book_db.BK_T_REQUEST as R
left join
(select
  book_db.BK_T_REQUEST_CHEER.REQUEST_ID,
  book_db.BK_T_REQUEST_CHEER.MEM_ID,
  count(book_db.BK_T_REQUEST_CHEER.REQUEST_ID) as REQ_COUNT
 from
  book_db.BK_T_REQUEST_CHEER
 join
  book_db.BK_T_REQUEST on book_db.BK_T_REQUEST_CHEER.REQUEST_ID = book_db.BK_T_REQUEST.REQUEST_ID
 group by
  BK_T_REQUEST_CHEER.REQUEST_ID
 ) as RC
on
 R.REQUEST_ID = RC.REQUEST_ID
where
  DEL_FLG = 0
;