SELECT
    B.BOOK_ID,
    B.TITLE,
    B.AUTHOR,
    B.TAG_IDS,
    B.OUTLINE,
    B.BOOK_IMG,
    LM.LEND_ID,
    LM.MEM_ID,
    LM.LEND_STATUS,
    LM.MEM_NAME,
    FC.FAV_COUNT,
    LC.LEND_COUNT
FROM
    book_db.BK_M_BOOK as B
LEFT JOIN
    (SELECT
		book_db.BK_T_LEND.BOOK_ID,
		book_db.BK_T_LEND.LEND_ID,
		book_db.BK_T_LEND.MEM_ID,
		book_db.BK_T_LEND.LEND_STATUS,
		book_db.M_MEM_BASIC.MEM_NAME
	FROM
		book_db.BK_T_LEND
	JOIN
		book_db.M_MEM_BASIC ON book_db.BK_T_LEND.MEM_ID = book_db.M_MEM_BASIC.MEM_ID
	WHERE
		LEND_STATUS = 11) as LM
ON
	B.BOOK_ID = LM.BOOK_ID
LEFT JOIN
	(SELECT
		book_db.BK_T_FAVORITE.BOOK_ID,
		COUNT(BOOK_ID) as FAV_COUNT
	FROM
		book_db.BK_T_FAVORITE
	GROUP BY
		BOOK_ID) as FC
ON
	B.BOOK_ID = FC.BOOK_ID
LEFT JOIN
	(SELECT
		book_db.BK_T_LEND.BOOK_ID,
		COUNT(BOOK_ID) as LEND_COUNT
	FROM
		book_db.BK_T_LEND
	group by
		BOOK_ID) as LC
ON
	B.BOOK_ID = LC.BOOK_ID;